// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVBVjqQz3-gUaQArwaUaUOjPMwZ2K-dfg',
    appId: '1:184103867068:web:c1279fdb1df6ba7a73f6b9',
    messagingSenderId: '184103867068',
    projectId: 'medireminder-e494b',
    authDomain: 'medireminder-e494b.firebaseapp.com',
    storageBucket: 'medireminder-e494b.firebasestorage.app',
    measurementId: 'G-7HDMY0C0D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW92JGlU0CvUxbh2ZGa3ZeHqeik8_4EXw',
    appId: '1:184103867068:android:46049414ef9439ab73f6b9',
    messagingSenderId: '184103867068',
    projectId: 'medireminder-e494b',
    storageBucket: 'medireminder-e494b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RZYZY0ZorT_UDPS_4ZMmiT1FthYD0Zs',
    appId: '1:184103867068:ios:940448f367a8709673f6b9',
    messagingSenderId: '184103867068',
    projectId: 'medireminder-e494b',
    storageBucket: 'medireminder-e494b.firebasestorage.app',
    iosBundleId: 'com.example.beckyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7RZYZY0ZorT_UDPS_4ZMmiT1FthYD0Zs',
    appId: '1:184103867068:ios:940448f367a8709673f6b9',
    messagingSenderId: '184103867068',
    projectId: 'medireminder-e494b',
    storageBucket: 'medireminder-e494b.firebasestorage.app',
    iosBundleId: 'com.example.beckyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVBVjqQz3-gUaQArwaUaUOjPMwZ2K-dfg',
    appId: '1:184103867068:web:07cce60330aaae3b73f6b9',
    messagingSenderId: '184103867068',
    projectId: 'medireminder-e494b',
    authDomain: 'medireminder-e494b.firebaseapp.com',
    storageBucket: 'medireminder-e494b.firebasestorage.app',
    measurementId: 'G-CV1VPBRQ9V',
  );
}
